export const SESSION_VALIDATE_TOKEN = 'SESSION_VALIDATE_TOKEN';
export const SESSION_RENEW_TOKEN = 'SESSION_RENEW_TOKEN';
export const SESSION_FETCH_TOKEN = 'SESSION_FETCH_TOKEN';
export const SESSION_FETCH_USER = 'SESSION_FETCH_USER';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
